### ISSUE TITLE
Missing 1.5.1 for Goodyear (Bose700)

### ISSUE THREAD

**Issue by alkuzad** [bosefirmware/ced#13]
This is new firmware bose is pushing for fixing 1.4.2 red/white light bricking issue. If you would need some help obtaining that from someone who has the hardware, please let me know

**Comment by bosefirmware** [comment]
Because Bose does not allow you to update to 1.5.1 if your headphones are running firmware lower than 1.4.2, it was decided not to upload that version yet as there might be a reason Bose does not allow this. This is the first time we've seen Bose do this so there might be a good reason for it and do not wish to cause any issues with anyone's headphones.

That is why 1.4.2 has been kept up so people could upgrade to that version here and then use the app to upgrade to 1.5.1.
