### ISSUE TITLE
Firmware out of date

### ISSUE THREAD

**Issue by dmeehl** [bosefirmware/ced#17]
The webpage indicates the firmware is out of date and prompts to re-download.
The version has been updated to 7.0.6.4815. Im running on mac and but when I used the hex editor to change the version string, the updater no longer opens. Any ideas what I did wrong?

**Comment by jefro108** [comment]
I think you mean that the Bose Updater app is out of date rather than the firmware. 

Using instructions from https://github.com/bosefirmware/ced/issues/12#issuecomment-691391269 I opened 0xED on my Mac to edit the version to 7.0.5.415 (while the app was quit) at `/Applications/Bose Updater.app/Contents/MacOS/Bose Updater` and then ran the instruction in terminal `xattr -cr /Applications/"Bose Updater.app" `. 

I then launched the Bose Updater app - it took a while to realise that it didn't need to download a new version,  but then it worked fine.

**Comment by dmeehl** [comment]
Yes, that's what I meant. Sorry for the typo.
The downloaded version at the bose site was 7.0.6.4815, so that's what I set it to with 0xED on my Mac. But after doing that, Bose Updater wont run.

**Comment by dmeehl** [comment]
Any way someone can post the updated (7.0.6.4815) version for mac? The app seems to be damaged after I update it with the hex editor, and I cant get it to run.

**Comment by bosefirmware** [comment]
Files updated

**Comment by dmeehl** [comment]
Well, I missed the window and they've updated the version again...
I wish I knew how to make the hex editor trick work. New version is 7.0.8.4837. Any chance you can bump it up again?

**Comment by jefro108** [comment]
I edited it according to the instructions above and it's working fine for me - you can download it from https://drive.google.com/file/d/1fjp8TQYPLkIihD7ZujPlbAmX_Q1JoE_K/view?usp=sharing as there is a 10MB upload limit on here

**Comment by dmeehl** [comment]
Yeah I edited the version string with the hex editor. Like I said, though, this results in an app that macos refuses to open. When I run it on commend line, it returns kill: 9. Are you repackaging the app somehow?

**Comment by jefro108** [comment]
That Google Drive link is to the app that is now working on my MacBook Pro 😊
